# 并发操作的同步

## 凭借条件变量等待条件成立

- `std::condition_variable`
- `std::condition_variable_any`

`std::condition_variable` 仅限与 `std::mutex` 一起使用。`std::condition_variable_any` 更为通用，能与任意符合成为互斥的最低标准的类型配合使用，但会产生额外开销。

### 使用 `std::condition_variable` 等待处理数据

在 `wait()` 的调用期间，条件变量可以多次查验给定的条件，次数不受限制；在查验时，互斥总会被锁住；另外，当且仅当传入的判定函数返回true时(它判断条件成立)，`wait()` 才会立即返回，而互斥仍被锁住；当判定函数返回false时，`wait()` 解锁互斥，并令线程进入阻塞状态或等待状态。如果线程重新获得互斥，并且查验条件，而这一行为却不是直接相应其他线程的通知，则称之为伪唤醒，按照C++标准的规定，这种伪唤醒出现的数量和频率都不确定，因此若判定函数有副作用，则不建议选取它来查验条件。因为在中途要解锁然后重新加锁，所以我们使用 `std::unique_lock`，`std::lock_guard` 无法提供这种灵活性。

```cpp
std::mutex mut;
std::queue<data_chunk> data_queue;
std::condition_variable data_cond;

void data_preparation_thread() {
    while(more_data_to_prepare()) {
        const data_chunk data = prepare_data();
        {
            std::lock_guard<std::mutex> lk(mut);
            data_queue.push(data);
        }
        data_cond.notify_one();
    }
}

void data_processing_thread() {
    while(true) {
        std::unique_lock<std::mutex> lk(mut);
        data_cond.wait(lk, []{return !data_queue.empty();});
        data_chunk data = data_queue.front();
        data_queue.pop();
        lk.unlock();
        process(data);
        if(is_last_chunk(data)) break;
    }
}
```

## 使用 future 等待一次性事件发生

- `std::future<>` 独占future
- `std::shared_future<>` 共享future

同一事件仅仅允许关联唯一一个 `std::future` 实例，但可以关联多个 `std::shared_future` 实例，只要目标事件发生，与后者相关的所有实例就会同时就绪，并且它们全都可以访问与该目标事件关联的任何数据。模板参数就是关联数据的类型。**虽然future能用于线程间通信，但是future对象本身不提供同步访问，若多个线程需访问同一个future对象，必须使用互斥或其他同步方式进行保护。**

### 从后台任务返回值

#### 运用 `std::future` 取得异步任务的函数返回值

只要我们并不急需线程运算的值，就可以使用 `std::async()` 按异步方式启动任务。我们从 `std::async()` 函数处获得 `std::future` 对象（而非 `std::thread`） 对象，运行的函数一旦完成，其返回值就由该对象最后持有。若要用到这个值，只需在 future 对象上调用 `get()`，当前线程就会阻塞，以便 future 准备妥当并返回该值。

```cpp
#include <future>
#include <iostream>

int find_the_answer_to_ltuae();
void do_other_stuff();

int main() {
    std::future<int> the_answer = std::async(find_the_answer_to_ltuae);
    do_other_stuff();
    std::cout << "The answer is " << the_answer.get() << std::endl;
}
```

在调用 `std::async()` 时，可以接收附加参数，进而传递给任务函数作为其参数，此方式与 `std::thread` 的构造函数相同。 

我们还可以给 `std::async()` 补充一个参数，以指定采用哪种运行方式。参数的类型是 `std::launch`，其值可以是 `std::launch::deferred` 或 `std::launch::async`。前者指定在当前线程上延后调用任务函数，等到在 future 上调用了 `wait()` 或 `get()`，任务函数才会执行；后者指定必须另外开启专属的线程，在其上运行任务函数。该参数的值还可以是 `std::launch::deferred | std::launch::async`，表示由 `std::async()` 的实现自行选择运行方式，这是参数的默认值。

### 关联 future 实例和任务

`std::packaged_task<>` 连结了 future 对象与函数(或可调对象)。`std::packaged_task<>` 对象在执行任务时，会调用关联的函数，把返回值保存为 future 的内部数据，并令 future 准备就绪。

`std::packaged_task<>` 是类模板，其模板参数是函数签名。它具有成员函数 `get_future`，返回 `std::future<>` 实例，该 future 的特化类型取决于函数签名所指定的返回值。 `std::packaged_task<>` 还具备函数调用操作符，它的参数取决于函数签名的参数列表。

以下代码以 `std::packaged_task<std::string(std::vector<char>*, int)>` 为例，展示特化的类定义：

```cpp
template<>
class packaged_task<std::string(std::vector<char>*, int)> {
public:
    template<typename Callable>
    explicit packaged_task(Callable&& f);
    std::future<std::string> get_future();
    void operator()(std::vector<char>*, int);
}
```

### 将异常保存到 future 中

若经由 `std::async()` 调用的函数抛出异常，则会被保存到 future 中，代替本该设定的值，future 随之进入就绪状态，等到其成员函数 `get()` 被调用，存储在内的异常即被重新抛出。若我们把任务函数包装在 `std::packaged_task` 对象内，也依然如此，若包装的任务函数在执行时抛出异常，则会代替本应求得的结果，被保存到 future 内并使其准备就绪，只要调用 `get()`，该异常就会被再次抛出。对于 `std::promise`，如果我们不想保存值，而想保存异常，就不应该调用 `set_value()`，而应调用成员函数 `set_exception()`，若算法的并发实现会抛出异常，则该函数通常可用于其 catch 块中，捕获异常并装填 promise。

### std::promise

`std::promise` 常配合 `std::future` 使用，可以在一个线程中保存一个值，供相绑定的 future 对象在另一个线程中取用。

```cpp
void thread_func1(std::promise<int>& p) {
    std::this_thread::sleep_for(std::chrono::seconds(5));
    int value = 233;
    std::cout << "send value: " << value << std::endl;
    p.set_value(value);
}

void thread_func2(std::future<int>& f) {
    auto value = f.get();
    std::cout << "receive value: " << value << std::endl;
}

int main() {
    std::promise<int> p1;
    std::future<int> f1 = p1.get_future();
    std::thread t1(thread_func1, std::ref(p1));
    std::thread t2(thread_func2, std::ref(f1));
    t1.join();
    t2.join();

    return 0;
}
```

### 将异常保存到 std::promise 中

```cpp
extern std::promise<double> some_promise;
try {
    some_promise.set_value(calculate_value());
} catch(...) {
    some_promise.set_exception(std::current_exception()); // 捕获抛出的异常
}

// 或使用 `std::make_exception_ptr` 直接保存新异常，而不触发抛出行为
some_promise.set_exception(std::make_exception_ptr(std::logic_error("foo")));
```
### 从 std::future 转移归属权到 std::shared_future 中
```cpp
std::promise<int> p;
std::future<int> f(p.get_future());
assert(f.valid());		// f 有效
std::shared_future<int> sf(std::move(f));
assert(!f.valid());		// f 不再有效
assert(sf.valid());		// sf 开始生效

std::promise<int> p2;
std::shared_future<int> sf2 = p2.get_future().share();	// 使用 share() 直接创建
assert(sf2.valid());
```
